@startuml
'https://plantuml.com/sequence-diagram

title Leverage sequence diagram \n\n Administration

autonumber

actor "Liquidity\nProvider" as provider
actor Trader as trader
actor Anyone as any
actor Admin as admin
participant Leverage as lc
participant PendingOrders as poc
participant EventLifeCycle as elc
participant PredictionPool as pp

admin -> lc: Set max liquidity usage threshold (percent)
any -> lc: Get liquidity usage threshold
lc --> any: Show liquidity usage threshold

newpage Add Liquidity

provider -> lc: Put liquidity (amount)
lc --> provider: Liquidity tokens
any -> lc: Get liquidity amount by address
lc --> any: Show liquidity amount
provider -> lc: Withdraw liquidity (amount)
lc -> lc: Check available and\n free(not used in orders) liquidity
lc --> provider: return liquidity
any -> lc: Get free liquidity
lc --> any: Show free liquidity


newpage Execute leveraged order
group Create leveraged order
trader -> lc: Create leveraged order (amount, max loss percent, eventId)
lc -> lc: Check if liquidity is enough\nfor the max possible order amount
lc -> lc: Check max order keeps\n5% liquidity free threshold
lc -> lc: Create leverage record\n(user, leverage, orderId)
lc -> poc: Create Order (amount)
   group leverage response
       alt unsuccessful case
           lc --> trader: Error <reason>
       end
   end
end

any -> lc: Get leverage record ids by account
lc -->: Show leverage record ids array for an account
any -> lc: Get leverage record details by leverage record id
lc -->: Show leverage record details
@enduml